// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('vitepress')['Content']
    ZeImage: typeof import('./.vitepress/theme/components/ZeImage.vue')['default']
    ZeNavbar: typeof import('./.vitepress/theme/components/ZeNavbar.vue')['default']
    ZImage: typeof import('./.vitepress/theme/components/ZImage.vue')['default']
    ZNavbar: typeof import('./.vitepress/theme/components/ZNavbar.vue')['default']
    ZzImage: typeof import('./.vitepress/theme/components/ZzImage.vue')['default']
  }
}
