// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('vitepress')['Content']
    TheNavbar: typeof import('./.vitepress/theme/components/TheNavbar.vue')['default']
    VPImage: typeof import('./.vitepress/theme/components/VPImage.vue')['default']
  }
}
